### ISSUE TITLE
Getting an very unspecific error called "error"

### ISSUE THREAD

**Issue by theirishpenguin** [christophehurpeau/deep-freeze-es6#2] opened 2016-07-26 11:16 UTC
I just get an error saying "Error" where I've noted HERE below...

```
module.exports = function deepFreeze(obj) {
    if (obj instanceof Map) {
        obj.clear = obj.delete = obj.set = function () {
            throw new Error('map is read-only');
        };
    } else if (obj instanceof Set) {
        obj.add = obj.clear = obj.delete = function () {
            throw new Error('set is read-only');
        };
    }

    Object.getOwnPropertyNames(obj).forEach(function (name) { <--- HERE
        var prop = obj[name];

        // Freeze prop if it is an object
        if (typeof prop == 'object' && !Object.isFrozen(prop)) {
            deepFreeze(prop);
        }
    });

    // Freeze self
    return Object.freeze(obj);
}


/*****************
 ** WEBPACK FOOTER
 ** ./~/deep-freeze-es6/index.js
 ** module id = 575
 ** module chunks = 0
 **/
```

**Comment by christophehurpeau** [comment] 2016-07-26 11:59
Can you help me reproduce the bug ? Do you have more specifics ?

**Comment by theirishpenguin** [comment] 2016-07-26 12:57
Sure. I can try :-) I call deepFreeze() on a Highchart.Point instance that I gets generated in the click event of a stacked bar in Highcharts when I get the error.

I have tweaked a JSFiddle of an existing Highchart demo to illustrate where this occurs (however this demo isn't in ES6).

http://jsfiddle.net/kk04ow4p/

Here is the Highchart Point API reference in case it's of use http://api.highcharts.com/highcharts#Point

Does any of that help?

**P.S. Before I tried your library...**
I had previously been trying standard deep-freeze npm package (ie. not designed for strict mode or ES6) and was getting the error, "TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them"

I then tried the deep-freeze-strict library and got the error, "TypeError: Method Map.prototype.size called on incompatible receiver [object Object]"

**Comment by christophehurpeau** [comment] 2016-07-26 13:06
Should be fixed by https://github.com/christophehurpeau/deep-freeze-es6/commit/9ae142022ef4844524f13fcdbcbc9613da37b5c4, can you confirm ?

**Comment by theirishpenguin** [comment] 2016-07-26 13:30
Thanks for your quick reply @christophehurpeau.

I retested with this and I get the error on the line marked with HERE below...

```
// 19.1.2.12 Object.isFrozen(O)
var isObject = __webpack_require__(89);

__webpack_require__(132)('isFrozen', function($isFrozen){
  return function isFrozen(it){
    return isObject(it) ? $isFrozen ? $isFrozen(it) : false : true; // <---- HERE
  };
});

/*****************
 ** WEBPACK FOOTER
 ** ./~/babel-polyfill/~/core-js/modules/es6.object.is-frozen.js
 ** module id = 141
 ** module chunks = 0
 **/
```

The error just says "error".

**Comment by christophehurpeau** [comment] 2016-07-26 14:28
Cannot reproduce: http://jsfiddle.net/christophehurpeau/ac388ywj/1/

**Comment by christophehurpeau** [comment] 2016-07-26 15:32
Anyway, I don't think you should freeze an event object, because inside this event you have objects like should not be froze (like a dom element). Closing, since the bug was fixed

**Closed by christophehurpeau** 2016-07-26 15:32 UTC

**Comment by theirishpenguin** [comment] 2016-07-26 15:38
Sure. If I see this problem in a simpler object then I will reraise. One final thing on this - should you be able to deeply freeze an object that is already deeply frozen? eg. This small modification to the jsfiddle throws a error http://jsfiddle.net/tan5yrey

Anyway, happy to leave this bug closed unless I can come up with a better test example. Thanks @christophehurpeau

**Comment by christophehurpeau** [comment] 2016-07-26 15:41
Yes you can deeply freeze an object already frozen - it won't do anything
I have no error with http://jsfiddle.net/tan5yrey

**Comment by theirishpenguin** [comment] 2016-07-26 16:01
Strange. It might just be that my Chrome browser is borked. I've tried it on Firefox and it is fine.

Leave this closed. Thanks for fixing.
